name: "Trend Anti-Malware Scan Service Action"
description: "Scan files looking for malware using Trend Anti-Malware Scan Service"
inputs:
  CLOUD_ONE_API_KEY:
    description: "Cloud One API Key"
    required: true
  REGION:
    description: "Cloud One Region"
    required: true
    default: "us-1"
  FILES:
    description: "List of files to scan, space separated. If not provided, all files in the repository will be scanned."
    required: true
    default: ""
  EXCLUSION:
    description: "File or folder to exclude. If not provided, '.git' folder will be excluded."
  HASH:
    description: "Boolean to decide if the hash of the file should be generated and returned. Defaults to false."
branding:
  icon: "shield"
  color: "red"
runs:
  using: "docker"
  image: "docker://ghcr.io/raphabot/amaas:latest"
  args:
    - --api_key
    - ${{ inputs.CLOUD_ONE_API_KEY }}
    - --region
    - ${{ inputs.REGION }}
    - $([ -z "$INPUT_FILES" ] && echo "" || echo "-f $INPUT_FILES")
    - $([ -z "$INPUT_EXCLUSION" ] && echo "" || echo "-exclude $INPUT_EXCLUSION")
    - $([ -z "$INPUT_HASH" ] && echo "" || echo "--hash")